set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g pane-border-lines simple
set -g pane-border-status off

unbind C-b
unbind C-a
set -g prefix M-a
bind-key M-a send-prefix

# Vim like pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Resize panes using Prefix + H, J, K, L
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Change from 0 based to 1 based because keyboard layout
set -g base-index 01
set -g pane-base-index 01
set-window-option -g pane-base-index 01
set-option -g renumber-windows on

# Vim-like copy/paste
set-window-option -g mode-keys vi
bind -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Alt+hjkl to switch panes (vim-style)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Alt+number to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Time Settings
# set -g status-right "%a %d %b - %I:%M %p"

# Colors
# Status bar catppuccin theme
# set -g status-style "bg=#181825,fg=#cdd6f4"
# # Copy-mode / selection
# set -g mode-style "bg=#313244,fg=#cdd6f4"
# # Messages
# set -g message-style "bg=#1e1e2e,fg=#cdd6f4"

# Status bar habamax theme 
set -g status-style "bg=#181818,fg=#c7c7c7"
# Copy-mode / selection
set -g mode-style "bg=#3a3a3a,fg=#c7c7c7"
# Messages
set -g message-style "bg=#181818,fg=#c7c7c7"
